<a href="https://colab.research.google.com/github/KepryDeSousa/Python_XPE_Bootcamp/blob/main/Numpy_Opera%C3%A7%C3%B5es_aritimeticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Operações aritimeticas
> Operações elemento a elemento 
>
> Broadcasting
> 
> Operações matriciais


In [1]:
import numpy as np 

## Elemento a Elemento

O que são :?

operações que acada rodada é novamente reproduzida como
> Somas, Sub, Mulplicacoes ...


In [4]:
array = [1,2,3,4]
array1 = [1,2,3,4]
somas = []
for  i in range(4):
  somas.append(array[i]+array1[i])

In [5]:
somas

[2, 4, 6, 8]

### Broadcasting:

realizar calculos em matrizes com tamanhos distintos mais equivalentes

> Ex : Mulplicacoes matriciais

In [7]:
n = np.eye(2)
n*2

array([[2., 0.],
       [0., 2.]])

In [8]:
n

array([[1., 0.],
       [0., 1.]])

In [ ]:
#outros exemplos
#python puro use @ para multipicar matrizes ou np.dot (a,b)



# Aula_2

Funções aritimeticas
> Soma,Sub e multi

In [10]:
x = np.eye(2)
y = np.ones([2,2])
x,y

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 1.],
        [1., 1.]]))

In [11]:
#soma
print(x+y)

[[2. 1.]
 [1. 2.]]


In [14]:
#sub
print(x-y)
print(x - 2)

[[ 0. -1.]
 [-1.  0.]]
[[-1. -2.]
 [-2. -1.]]


In [13]:
#multi 
print(x*y)


[[1. 0.]
 [0. 1.]]


In [15]:
#div
print(x/y)

[[1. 0.]
 [0. 1.]]


O Broading cast ele acaba seghuindo as regras de operações em matrizes